### ISSUE TITLE
Would you happen to have the solution for Q6 in hw1?

### ISSUE THREAD

**Issue by codeOfRobin** [danielfm/edx-learning-from-data#2]

**Comment by codeOfRobin** [comment]
I've been wracking my brain at this for an hour about now, What's not clear is the hypothesis I have to compare against. From what I can tell, there's one target function that agrees for every hypothesis from 1 to 4.

**Comment by codeOfRobin** [comment]
Never mind. I'm an idiot.

**Comment by kirbs-** [comment]
Glad you figured it out.
